In [25]:
import pandas as pd
import numpy as np

In [2]:
base = pd.read_csv('Raw-Data.csv')

In [3]:
base.head()

Country    Age       Gender  \
0               China    0-9         Male   
1               Italy  10-19       Female   
2                Iran  20-24  Transgender   
3  Republic of Korean  25-59          NaN   
4              France    60+          NaN   

                                            Symptoms  \
0  Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...   
1  Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing   
2                          Fever,Tiredness,Dry-Cough   
3                                    Fever,Tiredness   
4                                              Fever   

                        Experiencing_Symptoms  Severity    Contact  
0  Pains,Nasal-Congestion,Runny-Nose,Diarrhea      Mild        Yes  
1           Pains,Nasal-Congestion,Runny-Nose  Moderate         No  
2                      Pains,Nasal-Congestion    Severe  Dont-Know  
3                                       Pains      None        NaN  
4        Nasal-Congestion,Runny-Nose,Diarrhea       NaN        NaN

In [4]:
base_cleaned = pd.read_csv('Cleaned-Data.csv')

In [5]:
base_cleaned.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0   
1            1                   0              1                  0   
2            1                   0              1                  0   
3            1                   0              0                  1   
4            1                   0              0                  1   

   Severity_None  Severity_Severe  Contact_Dont-Know  Contact_No  Contact_Yes  \
0              0                0                  0           0            1   
1              0                0                  0           1            0   
2              0                0                  1           0            0   
3              0                0                  0           0            1   
4              0                0                  0           1            0   

   Country  
0    China  
1    China  
2    China  
3    China  
4    China  

[5 rows x 27 columns]

In [6]:
print(base.shape, base_cleaned.shape)

(16, 7) (316800, 27)


In [7]:
pd.DataFrame(np.unique(base_cleaned.Country, return_counts=True))

0       1        2      3      4      5          6                   7  \
0  China  France  Germany   Iran  Italy  Other  Other-EUR  Republic of Korean   
1  31680   31680    31680  31680  31680  31680      31680               31680   

       8      9  
0  Spain    UAE  
1  31680  31680

In [8]:
# UNir os dados de serveridade para poder usar como classificador.

In [9]:
join_columns = ['Severity_Severe', 'Severity_Moderate', 'Severity_Mild' ,'Severity_None']

# Join columns to use classifier
def join_dummies(df, columns, new_column_name='Join_columns'):
    join_columns = df[columns]
    new_df = []
    for i in range(len(join_columns)):
        ind = join_columns.iloc[i].idxmax()
        new_df.append(ind)

    df[new_column_name] = new_df

join_dummies(base_cleaned, join_columns, new_column_name='Severity')

In [10]:
# Testar se todos so possuem um mesmo (Medo dos dados terem problemas)
df = base_cleaned[join_columns]
for i in range(len(base_cleaned)):
    s = df.iloc[i].sum()
    if s != 1:
        print(df.iloc[i])

In [11]:
base_cleaned.Severity.value_counts()

Severity_Severe      79200
Severity_None        79200
Severity_Mild        79200
Severity_Moderate    79200
Name: Severity, dtype: int64

In [41]:
severity_base = base_cleaned.drop(join_columns, axis=1)
pd.set_option('display.max_columns', None)
severity_base.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  \
0             0      1                 1           1         1   
1             0      1                 1           1         1   
2             0      1                 1           1         1   
3             0      1                 1           1         1   
4             0      1                 1           1         1   

   None_Experiencing  Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+  \
0                  0        1          0          0          0        0   
1                  0        1          0          0          0        0   
2                  0        1          0          0          0        0   
3                  0        1          0          0          0        0   
4                  0        1          0          0          0        0   

   Gender_Female  Gender_Male  Gender_Transgender  Contact_Dont-Know  \
0              0            1                   0                  0   
1              0            1                   0                  0   
2              0            1                   0                  1   
3              0            1                   0                  0   
4              0            1                   0                  0   

   Contact_No  Contact_Yes Country           Severity  
0           0            1   China      Severity_Mild  
1           1            0   China      Severity_Mild  
2           0            0   China      Severity_Mild  
3           0            1   China  Severity_Moderate  
4           1            0   China  Severity_Moderate

In [13]:
# Separar dados de teste e treino

In [45]:
# Categorical Encode
import category_encoders as ce
encoder = ce.OrdinalEncoder(cols=['Severity', 'Country'], return_df=True)
encoder.fit(severity_base)

/home/beloin/anaconda3/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


OrdinalEncoder(cols=['Severity', 'Country'],
               mapping=[{'col': 'Severity', 'data_type': dtype('O'),
                         'mapping': Severity_Mild        1
Severity_Moderate    2
Severity_Severe      3
Severity_None        4
NaN                 -2
dtype: int64},
                        {'col': 'Country', 'data_type': dtype('O'),
                         'mapping': China                  1
Italy                  2
Iran                   3
Republic of Korean     4
France                 5
Spain                  6
Germany                7
UAE                    8
Other-EUR              9
Other                 10
NaN                   -2
dtype: int64}])

In [46]:
encoded_base = encoder.transform(severity_base)
encoded_base

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0           1          1          1                        1            1   
1           1          1          1                        1            1   
2           1          1          1                        1            1   
3           1          1          1                        1            1   
4           1          1          1                        1            1   
...       ...        ...        ...                      ...          ...   
316795      0          0          0                        0            0   
316796      0          0          0                        0            0   
316797      0          0          0                        0            0   
316798      0          0          0                        0            0   
316799      0          0          0                        0            0   

        None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  \
0                  0      1                 1           1         1   
1                  0      1                 1           1         1   
2                  0      1                 1           1         1   
3                  0      1                 1           1         1   
4                  0      1                 1           1         1   
...              ...    ...               ...         ...       ...   
316795             1      0                 0           0         0   
316796             1      0                 0           0         0   
316797             1      0                 0           0         0   
316798             1      0                 0           0         0   
316799             1      0                 0           0         0   

        None_Experiencing  Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+  \
0                       0        1          0          0          0        0   
1                       0        1          0          0          0        0   
2                       0        1          0          0          0        0   
3                       0        1          0          0          0        0   
4                       0        1          0          0          0        0   
...                   ...      ...        ...        ...        ...      ...   
316795                  1        0          0          0          0        1   
316796                  1        0          0          0          0        1   
316797                  1        0          0          0          0        1   
316798                  1        0          0          0          0        1   
316799                  1        0          0          0          0        1   

        Gender_Female  Gender_Male  Gender_Transgender  Contact_Dont-Know  \
0                   0            1                   0                  0   
1                   0            1                   0                  0   
2                   0            1                   0                  1   
3                   0            1                   0                  0   
4                   0            1                   0                  0   
...               ...          ...                 ...                ...   
316795              0            0                   1                  0   
316796              0            0                   1                  1   
316797              0            0                   1                  0   
316798              0            0                   1                  0   
316799              0            0                   1                  1   

        Contact_No  Contact_Yes  Country  Severity  
0                0            1        1         1  
1                1            0        1         1  
2                0            0        1         1  
3                0            1        1         2  
4                1            0        1         2  
...            ...        

In [89]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

no_country_base = severity_base.drop('Country',axis=1)
X = no_country_base.iloc[:,:21]
y = no_country_base.iloc[:,22]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)
pred_tree = tree_model.predict(X_test)
acc_tree = accuracy_score(y_test, pred_tree)
cf_tree = confusion_matrix(y_test, pred_tree, )
acc_tree, cf_tree

(0.1320496632996633,
 array([[5061, 8127, 5720, 4700],
        [9647, 3448, 5838, 4686],
        [9770, 7212, 2292, 4692],
        [9604, 7240, 5254, 1749]]))

In [78]:
def test_model(model):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    cf = confusion_matrix(y_test, pred)
    return acc, cf

In [88]:
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB()

test_model(gaussian_model)

(0.13076599326599325,
 array([[4973, 7669, 6187, 4941],
        [9430, 3191, 6221, 4970],
        [9530, 6809, 2483, 5024],
        [9523, 6816, 5492, 1781]]))

In [87]:
from sklearn.ensemble import RandomForestClassifier
random_model = RandomForestClassifier()
test_model(random_model)

(0.13076599326599325,
 array([[4973, 7669, 6187, 4941],
        [9430, 3191, 6221, 4970],
        [9530, 6809, 2483, 5024],
        [9523, 6816, 5492, 1781]]))

In [85]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
test_model(knn_model)

(0.13061868686868686,
 array([[4934, 7800, 6022, 4902],
        [9510, 3259, 5951, 5002],
        [9476, 7019, 2351, 4980],
        [9557, 7025, 5382, 1870]]))